<?php
/**
 * Copyright © Two.inc All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFieldInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Component\Form as MagewireFormComponent;
use Two\GatewayHyva\ViewModel\CheckoutConfig;

/** @var Template $block */
/** @var EntityFieldInterface $element */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var MagewireFormComponent $magewire */
/** @var CheckoutConfig $viewModel */

$configModel = $viewModels->require(CheckoutConfig::class);
$isCompanySearchEnabled = $configModel->getIsCompanySearchEnabled();
/** @Tailwind md:w-1/4 md:w-2/4 md:w-3/4 md:w-4/4 mb-2 */
$element = $block->getData("element");
$attributes = $element->getAttributes();
$renderer = $element->getRenderer();
$form = $block->getData("form");
?>
<div class="w-full font-medium text-gray-700 <?= /* @noEscape */ $element->isRequired()
        ? "required"
        : "not-required" ?>">
    <?= /* @noEscape */ $renderer->renderLabel($element) ?>
    <?= /* @noEscape */ $renderer->renderBefore($element) ?>

    <div class="block font-medium text-gray-700">
        <div x-data="twoGatewayHyvaCompanySearchField" class="relative">
            <input type="text" class="<?= $escaper->escapeHtmlAttr(
                $element->renderClass([
                    "block w-full form-input grow renderer-text",
                ]),
            ) ?>"
            <?php if ($element->hasAttributes()): ?>
                <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
            <?php endif; ?> autocomplete="off"
            @input.debounce.200ms="getItems"
            />
            <!-- Search for company link (shows in manual mode) -->
            <div x-show="manualMode" class="mt-1 text-right">
                <span @click="enableSearch" class="text-blue-600 text-sm cursor-pointer">
                    <?= $escaper->escapeHtml(__("Search for company")) ?>
                </span>
            </div>
            <!-- Search Results Dropdown -->
            <div
                x-show="showDropdown"
                class="w-full z-40 border border-gray-200 rounded-b-lg bg-white absolute mt-1 shadow-lg"
            >
                <div class="flex flex-col w-full max-h-[250px] overflow-y-auto">
                    <template x-for="(item, index) in items" :key="item.companyId">
                        <div
                            :data-index="index"
                            @click="handleItemClick"
                            class="cursor-pointer hover:bg-gray-100 p-2 border-b border-gray-100"
                        >
                            <span x-html="item.companyDisplayName"></span>
                        </div>
                    </template>
                </div>
                <!-- Enter manually link inside dropdown -->
                <div class="px-2 py-3 border-t border-gray-200">
                    <span @click="enterManually" class="text-blue-600 text-sm cursor-pointer">
                        <?= $escaper->escapeHtml(
                            __("Enter details manually"),
                        ) ?>
                    </span>
                </div>
            </div>
        </div>
        <?php if ($element->hasTooltip()): ?>
            <?= /* @noEscape */ $element
                    ->getRenderer()
                    ->renderTooltip($element) ?>
        <?php endif; ?>
    </div>
    <?= /* @noEscape */ $element->getRenderer()->renderAfter($element) ?>
</div>
